create table if not exists ai_link_metadata (
  id bigint generated by default as identity primary key,
  short_code varchar(64) not null unique,
  original_url varchar(2048) not null,
  status varchar(24) not null,
  provider varchar(64) not null,
  prompt_version varchar(64) not null,
  title varchar(255),
  summary varchar(1000),
  category varchar(120),
  icon varchar(16),
  suggested_alias varchar(120),
  tags varchar(500),
  error_message varchar(1000),
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null,
  completed_at timestamp with time zone
);

create index if not exists idx_ai_link_metadata_short_code on ai_link_metadata(short_code);
create index if not exists idx_ai_link_metadata_status on ai_link_metadata(status);
