create table if not exists app_roles (
    id bigint generated by default as identity primary key,
    name varchar(32) not null unique
);

insert into app_roles (name) values ('ADMIN');
insert into app_roles (name) values ('USER');

alter table app_users
    add column if not exists role_id bigint;

update app_users
set role_id = (
    select id from app_roles where name = 'ADMIN'
)
where upper(role) = 'ADMIN'
  and role_id is null;

update app_users
set role_id = (
    select id from app_roles where name = 'USER'
)
where upper(role) = 'USER'
  and role_id is null;

alter table app_users
    alter column role_id set not null;

alter table app_users
    add constraint fk_app_users_role foreign key (role_id) references app_roles(id);

create index if not exists idx_app_users_role_id on app_users(role_id);

alter table app_users
    drop column if exists role;
