create table if not exists app_refresh_tokens (
    id bigint generated by default as identity primary key,
    token_hash varchar(128) not null unique,
    user_id bigint not null,
    created_at timestamp with time zone not null,
    expires_at timestamp with time zone not null,
    revoked_at timestamp with time zone null
);

alter table app_refresh_tokens
    add constraint fk_app_refresh_tokens_user foreign key (user_id) references app_users(id);

create index if not exists idx_app_refresh_tokens_user_id on app_refresh_tokens(user_id);
create index if not exists idx_app_refresh_tokens_expires_at on app_refresh_tokens(expires_at);
