create table if not exists click_events (
    id bigint generated by default as identity primary key,
    short_code varchar(32) not null,
    clicked_at timestamp with time zone not null,
    ip_address varchar(64),
    user_agent varchar(512),
    referrer varchar(2048),
    country varchar(64),
    browser_family varchar(64),
    device_type varchar(64)
);

create index if not exists idx_click_events_short_code on click_events(short_code);
