alter table app_users
    add column if not exists email varchar(255);

alter table app_users
    add column if not exists email_verified_at timestamp with time zone null;

create unique index if not exists idx_app_users_email on app_users(email);

create table if not exists app_account_action_tokens (
    id bigint generated by default as identity primary key,
    token_hash varchar(128) not null unique,
    type varchar(32) not null,
    user_id bigint not null,
    created_at timestamp with time zone not null,
    expires_at timestamp with time zone not null,
    consumed_at timestamp with time zone null
);

alter table app_account_action_tokens
    add constraint fk_app_account_action_tokens_user foreign key (user_id) references app_users(id);

create index if not exists idx_app_account_action_tokens_user_id on app_account_action_tokens(user_id);
create index if not exists idx_app_account_action_tokens_expires_at on app_account_action_tokens(expires_at);
