create table if not exists bootstrap_marker (
    id bigint generated by default as identity primary key,
    name varchar(64) not null,
    created_at timestamp with time zone not null default current_timestamp
);
