create table if not exists short_links (
    id bigint generated by default as identity primary key,
    code varchar(32) not null unique,
    original_url varchar(2048) not null,
    custom_alias varchar(64) unique,
    created_at timestamp with time zone not null,
    expires_at timestamp with time zone null,
    click_count bigint not null default 0
);
