create table if not exists app_users (
    id bigint generated by default as identity primary key,
    username varchar(128) not null unique,
    password_hash varchar(255) not null,
    role varchar(32) not null,
    enabled boolean not null default true,
    created_at timestamp with time zone not null,
    last_login_at timestamp with time zone null
);

alter table short_links
    add column if not exists owner_username varchar(128);

create index if not exists idx_short_links_owner_username on short_links(owner_username);
