create table if not exists app_roles (
    id bigint generated by default as identity primary key,
    name varchar(32) not null unique
);

insert into app_roles (name)
select 'ADMIN'
where not exists (
    select 1 from app_roles where name = 'ADMIN'
);

insert into app_roles (name)
select 'USER'
where not exists (
    select 1 from app_roles where name = 'USER'
);

alter table app_users
    add column if not exists role_id bigint;

update app_users u
set role_id = r.id
from app_roles r
where upper(u.role) = r.name
  and u.role_id is null;

alter table app_users
    alter column role_id set not null;

alter table app_users
    add constraint fk_app_users_role foreign key (role_id) references app_roles(id);

create index if not exists idx_app_users_role_id on app_users(role_id);

alter table app_users
    drop column if exists role;
